ContaPizzaWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContaPizzaWeb.Models;

namespace ContaPizzaWeb.Controllers
{
    public class AdminController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Admin/

        public ActionResult Index()
        {
            var pizzasmodels = db.PizzasModels.Include(p => p.Func).Include(p => p.Mot);
            return View(pizzasmodels.Where(p => p.Status.Equals(("Pend"))).OrderBy(p => p.Func.Funcionario).ToList());
        }

        //
        // GET: /Admin/Details/5

        public ActionResult Details(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            return View(pizzamodels);
        }

        //
        // GET: /Admin/Create

        public ActionResult Create()
        {
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario");
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo");
            ViewBag.DataAtual = DateTime.Today;
            return View();
        }

        //
        // POST: /Admin/Create

        [HttpPost]
        public ActionResult Create(PizzaModels pizzamodels)
        {
            if (ModelState.IsValid)
            {
                db.PizzasModels.Add(pizzamodels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // GET: /Admin/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult Edit(PizzaModels pizzamodels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pizzamodels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // GET: /Admin/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            return View(pizzamodels);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            db.PizzasModels.Remove(pizzamodels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteReg(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            return View(pizzamodels);
        }
        

        [HttpPost, ActionName("DeleteReg")]
        public ActionResult DeleteRegConfirmed(int id)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            pizzamodels.Status = "Pago";
            pizzamodels.DataPag = DateTime.Today.ToString("dd/MM/yyyy");
            db.Entry(pizzamodels).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult AtualizaDetalhes(int IdPizza, string Detalhes)
        {
            try
            {
                PizzaModels pizzamodels = db.PizzasModels.Find(IdPizza);
                pizzamodels.Detalhes = Detalhes;
                db.Entry(pizzamodels).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { Status = 200, Mensagem = "Sucesso" });
            }
            catch (Exception ex)
            {
                return Json(new { Status = 500, Mensagem = ex.Message });
            }
        }
       

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ContaPizzaWeb/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContaPizzaWeb.Models;

namespace ContaPizzaWeb.Controllers
{
    public class FuncionariosController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Funcionarios/

        public ActionResult Index()
        {
            return View(db.FuncionariosModels.ToList());
        }

        //
        // GET: /Funcionarios/Details/5

        public ActionResult Details(int id = 0)
        {
            FuncionarioModels funcionariomodels = db.FuncionariosModels.Find(id);
            if (funcionariomodels == null)
            {
                return HttpNotFound();
            }
            return View(funcionariomodels);
        }

        //
        // GET: /Funcionarios/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Funcionarios/Create

        [HttpPost]
        public ActionResult Create(FuncionarioModels funcionariomodels)
        {
            if (ModelState.IsValid)
            {
                db.FuncionariosModels.Add(funcionariomodels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(funcionariomodels);
        }

        //
        // GET: /Funcionarios/Edit/5

        public ActionResult Edit(int id = 0)
        {
            FuncionarioModels funcionariomodels = db.FuncionariosModels.Find(id);
            if (funcionariomodels == null)
            {
                return HttpNotFound();
            }
            return View(funcionariomodels);
        }

        //
        // POST: /Funcionarios/Edit/5

        [HttpPost]
        public ActionResult Edit(FuncionarioModels funcionariomodels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionariomodels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionariomodels);
        }

        //
        // GET: /Funcionarios/Delete/5

        public ActionResult Delete(int id = 0)
        {
            FuncionarioModels funcionariomodels = db.FuncionariosModels.Find(id);
            if (funcionariomodels == null)
            {
                return HttpNotFound();
            }
            return View(funcionariomodels);
        }

        //
        // POST: /Funcionarios/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            FuncionarioModels funcionariomodels = db.FuncionariosModels.Find(id);
            db.FuncionariosModels.Remove(funcionariomodels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ContaPizzaWeb/Controllers/HistoricoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContaPizzaWeb.Models;

namespace ContaPizzaWeb.Controllers
{
    public class HistoricoController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Historico/

        public ActionResult Index()
        {
            var pizzasmodels = db.PizzasModels.Include(p => p.Func).Include(p => p.Mot);
            return View(pizzasmodels.Where(p => p.Status.Equals(("Pago"))).ToList());
        }

        //
        // GET: /Historico/Details/5

        public ActionResult Details(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            return View(pizzamodels);
        }

        //
        // GET: /Historico/Create

        public ActionResult Create()
        {
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario");
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo");
            return View();
        }

        //
        // POST: /Historico/Create

        [HttpPost]
        public ActionResult Create(PizzaModels pizzamodels)
        {
            if (ModelState.IsValid)
            {
                db.PizzasModels.Add(pizzamodels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // GET: /Historico/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // POST: /Historico/Edit/5

        [HttpPost]
        public ActionResult Edit(PizzaModels pizzamodels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pizzamodels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdFunc = new SelectList(db.FuncionariosModels, "IdFunc", "Funcionario", pizzamodels.IdFunc);
            ViewBag.IdMot = new SelectList(db.MotivosModels, "IdMot", "Motivo", pizzamodels.IdMot);
            return View(pizzamodels);
        }

        //
        // GET: /Historico/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            if (pizzamodels == null)
            {
                return HttpNotFound();
            }
            return View(pizzamodels);
        }

        //
        // POST: /Historico/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PizzaModels pizzamodels = db.PizzasModels.Find(id);
            db.PizzasModels.Remove(pizzamodels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ContaPizzaWeb/Views/Admin/Create.cshtml
@using System.ComponentModel.DataAnnotations
@using System.Data.Entity.ModelConfiguration.Conventions
@using System.Drawing
@using System.Web.Mvc.Html
@using Microsoft.SqlServer.Server
@model ContaPizzaWeb.Models.PizzaModels

@{
    ViewBag.Title = "ContaPizza";
}

<h2>Registrar Pizza</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PizzaModels</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RegData)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegData)
            @Html.ValidationMessageFor(model => model.RegData)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdFunc, "Funcionário")
        </div>
        <div class="editor-field">
            @Html.DropDownList("IdFunc", String.Empty)
            @Html.ValidationMessageFor(model => model.IdFunc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdMot, "Motivo")
        </div>
        <div class="editor-field">
            @Html.DropDownList("IdMot", String.Empty)
            @Html.ValidationMessageFor(model => model.IdMot)
        </div>
        <br/>
        <p>
            <input type="submit" value="Registrar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContaPizzaWeb/Views/Admin/Delete.cshtml
@model ContaPizzaWeb.Models.PizzaModels

@{
    ViewBag.Title = "ContaPizzaWeb";
}

<h3>Deseja deletar o registro selecionado?</h3>
<fieldset>
    <legend>PizzaModels</legend>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.RegData)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RegData)
    </div>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Func.Funcionario)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Func.Funcionario)
    </div>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Mot.Motivo)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mot.Motivo)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Deletar" /> |
        @Html.ActionLink("Voltar", "Index")
    </p>
}

ContaPizzaWeb/Views/Admin/DeleteReg.cshtml
@model ContaPizzaWeb.Models.PizzaModels

@{
    ViewBag.Title = "ContaPizzaWeb";
}

<h3>Deseja dar baixa no registro selecionado?</h3>
<fieldset>
    <legend>PizzaModels</legend>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.RegData)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RegData)
    </div>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Func.Funcionario)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Func.Funcionario)
    </div>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Mot.Motivo)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mot.Motivo)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Pagar" /> |
        @Html.ActionLink("Voltar", "Index")
    </p>
}

ContaPizzaWeb/Views/Admin/Details.cshtml
@model ContaPizzaWeb.Models.PizzaModels

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PizzaModels</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RegData)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RegData)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Func.Funcionario)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Func.Funcionario)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mot.Motivo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mot.Motivo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataPag)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataPag)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.IdPizza }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContaPizzaWeb/Views/Admin/Edit.cshtml
@model ContaPizzaWeb.Models.PizzaModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset class="table">
        <legend>PizzaModels</legend>

        @Html.HiddenFor(model => model.IdPizza)

        <div class="editor-label">
            @Html.LabelFor(model => model.RegData)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegData)
            @Html.ValidationMessageFor(model => model.RegData)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdFunc, "Func")
        </div>
        <div class="editor-field">
            @Html.DropDownList("IdFunc", String.Empty)
            @Html.ValidationMessageFor(model => model.IdFunc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdMot, "Mot")
        </div>
        <div class="editor-field">
            @Html.DropDownList("IdMot", String.Empty)
            @Html.ValidationMessageFor(model => model.IdMot)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataPag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataPag)
            @Html.ValidationMessageFor(model => model.DataPag)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContaPizzaWeb/Views/Admin/Index.cshtml
@model IEnumerable<ContaPizzaWeb.Models.PizzaModels>

@{
    ViewBag.Title = "ContaPizzas";
}

<h2>
    @Html.ActionLink("ContaPizza", "Index", "Admin") |
    @Html.ActionLink("Atrasos", "Index", "Atrasos") |
    @Html.ActionLink("Funcionários", "Index", "Funcionarios") |
    @Html.ActionLink("Motivos", "Index", "Motivos") |
    @Html.ActionLink("Histórico", "Index", "Historico")
</h2>
    <h3>@Html.ActionLink("Adicionar Pizza", "Create")</h3>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegData)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Func.Funcionario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mot.Motivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Detalhes)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Func.Funcionario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mot.Motivo)
            </td>
            <td>
                <button id="toolTip Editar-Detalhes" class="btn btn-primary popover-show" title="Detalhes"
                        data-container="body" 
                        data-toggle="popover" 
                        data-idPizza="@item.IdPizza"
                        data-content="@item.Detalhes">
                    <a class="teste" href="#" data-toggle="modal" data-target="#myModal" style="text-decoration: none">?</a>
                </button>
            </td>
            <td>
                @Html.ActionLink("Pagar Pizza", "DeleteReg", new { @id=item.IdPizza })
            </td>
            <td>
                <a class="btn btn-danger btn-sm" href="@Url.Action("Delete", "Admin", new { @id=item.IdPizza})"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    }
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Detalhes</h4>
      </div>
      <div class="modal-body">
        <textarea style="resize:none; width:560px; height:100px" id="DetalhesMotivo" name="Detalhes"></textarea>
        <input type="hidden" id="IdPizza" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="AlterarDetalhes">Salvar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function() {


            $("a.teste").click(function () {
                var idPizza = $(this).parent().attr("data-idPizza");
                console.log(idPizza);
                $('#IdPizza').val(idPizza);
                $("#DetalhesMotivo").val($(this).parent().attr("data-content"));

            });

            $("#AlterarDetalhes").click(function () {
                var detalhes = $("#DetalhesMotivo").val();
                var idPizza = $("#IdPizza").val();
                $.ajax({
                    type: "POST",
                    url: "Admin/AtualizaDetalhes",
                    data: { 'IdPizza': idPizza, 'Detalhes': detalhes },
                    success: Sucesso,
                    dataType: 'json'
                });
            });            
        });
        function Sucesso(data) {
            if (data.Status == 200) {
                alert("Motivo atualizado com sucesso");
                location.reload();
            }
            else
                alert(data.Mensagem);
        }
    </script>
}
@section Estilo {
    <style type="text/css">
        a[data-toggle=modal]:link {text-decoration: none;color: #ffffff;background-color: #428bca}
        a[data-toggle=modal]:active {text-decoration: none;color: #ffffff;background-color: #428bca}
        a[data-toggle=modal]:visited {text-decoration: none;color: #ffffff;background-color: #428bca}
        a[data-toggle=modal]:hover {text-decoration: underline;color: #ffffff;background-color: #428bca}
        .btn-primary:hover,
        .btn-primary:focus,
        .btn-primary:active,
        .btn-primary.active {background-color: #428bca;border-color: #357ebd;}
    </style>
}